import React from 'react';
import Head from 'next/head';
import { Container, forwardRef, ContainerProps } from '@chakra-ui/react';
import Footer from './Footer';

interface LayoutProps extends ContainerProps {
  children: React.ReactNode;
  titlePage?: string;
  descriptionPage?: string;
}

const Layout: React.FC<LayoutProps> = forwardRef<LayoutProps, 'div'>(
  ({ children, titlePage = 'Create Next App', descriptionPage = 'Generated by create next app', ...rest }, ref) => (
    <Container maxWidth='container.sm' ref={ref} {...rest}>
      <Head>
        <title>{titlePage}</title>
        <meta name='description' content={descriptionPage} />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {children}
      <Footer />
    </Container>
  ),
);

export default Layout;
